apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "spec-test-1824"
  description: "Artifacts generator via Spec."
  annotations:
    github.com/project-slug: veecode-homolog/spect-test-1824
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: spec_project.yml
  links:
    - title: /viacep
      url: http://vkpr.platform.vee.codes/viacep
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - spect-test-1824
